### PR TITLE
Disabled login btn

### PR DESCRIPTION
**Pull request by TK-7728**
The disabling of the general login button was stopped at Spectest, so it was hastily made available to Develop as well.

### CODE REVIEW

**Comment by ItsukiKigoshi** [comment]
> 

What does this mean?
Did u disable “login button for 一般”?

**Comment by TK-7728** [comment]
> > The disabling of the general login button was stopped at Spectest, so it was hastily made available to Develop as well.
> 
> 
> 
> What does this mean?
> 
> Did u disable “login button for 一般”?

Yes

**Comment by hibiyahibiyahibiya** [comment]
一日目の時間が少しズレたそうなのでそこ修正お願いします
それ以外はOK出ました
@TK-7728

**Review by hibiyahibiyahibiya — APPROVED** [review]
どーぞ

**Pull request merged**
